### ISSUE TITLE
spearman_footrule_distance gives incorrect value for odd lengthed inputs

### ISSUE THREAD

**Issue by jakesherman** [thelahunginjeet/kbutil#1]
I am in the process of organizing various ordinal/rank correlation and distance measures into a Python package, and came upon the `spearman_footrule_distance` function here. I noticed a small mistake - in normalizing Spearman's footrule (sum of the absolute value rank differences) to a range of [0, 1], the normalizer, 0.5n^2, only works for even inputs, odd inputs should have a normalizer of 0.5(n + 1)(n - 1). 
### Example

``` python
c = [1,2,3,4,5]  # input has length 5, so it's odd
d = [5,4,3,2,1]
spearman_footrule_distance(c, d)  # 0.96, should be 1.0
```
### Reference

"Comparing top k lists" by Fargin et al. 2003, http://researcher.watson.ibm.com/researcher/files/us-fagin/topk.pdf. To quote:

```
Spearman’s footrule metric is the L1 distance between two permutations. Formally, it is defined by
F(σ1, σ2) = Pn
i=1 |σ1(i) − σ2(i)|. The maximum value of F(σ1, σ2) is n
2/2 when n is even, and (n +
1)(n−1)/2 when n is odd. As with Kendall’s tau, the maximum occurs when σ1 is the reverse of σ2. Later,
we shall discuss a variation of Spearman’s footrule called “Spearman’s rho.”
```

**Comment by jakesherman** [comment]
I haven't got a chance to check, but this issue may also be present in `RankAggregator.footrule_aggregation` in the `pyrankagg` package.

**Comment by thelahunginjeet** [comment]
Hi Jake,

Thank you for catching that!  I've fixed it in kbutil.  It is indeed a problem in pyrankagg also; I'm closing the issue for kbutil and I'll fix it there as well.
